#!/usr/bin/env python3
"""Generate docker-content/manifest.json — wires each notebook `##` section to the
`docker` scene with a per-section highlight list of dk-* node ids and an audio stem.

The notebook is the source of truth; this only *wires*. Headings must match the
notebook `## ` text (the app matches by normalized heading: lowercased, backticks
stripped, whitespace collapsed). Section 01 of each notebook ("What's covered") is
the full-map hook (no highlight, no audio). audio stem == the tts/ filename stem.
"""
import json
from pathlib import Path

S = "docker"  # every section rides the one dense scene

# Per module: (pid, title, notebook, [ (heading, stem, spine, [highlight ids]) ... ])
# The hook ("What's covered") is added automatically as the first section.
MODULES = [
    ("01-getting-started", "Getting Started with Docker",
     "notebooks/01-getting-started-with-docker.ipynb", [
        ("What is a container?", "01-02-what-is-a-container", True, ["dk-container"]),
        ("Image vs container", "01-03-image-vs-container", True, ["dk-image", "dk-container"]),
        ("Why Docker matters", "01-04-why-docker-matters", False, ["dk-registry", "dk-orchestrate"]),
        ("Getting Docker installed", "01-05-getting-docker-installed", False, ["dk-engine"]),
        ("Your first container — `docker run hello-world`", "01-06-your-first-container", True,
         ["dk-run", "dk-dockerd", "dk-registry", "dk-container"]),
        ("How Docker actually works — the architecture", "01-07-how-docker-works", True,
         ["dk-cli", "dk-engine"]),
        ("Anatomy of a `docker` command", "01-08-anatomy-of-a-docker-command", False, ["dk-cli"]),
        ("The core container lifecycle", "01-09-the-container-lifecycle", True, ["dk-lifecycle"]),
        ("Container exit codes", "01-10-container-exit-codes", False, ["dk-stop", "dk-rm"]),
        ("Getting help — `--help`, `docker help`, and the docs", "01-11-getting-help", False, ["dk-cli"]),
        ("Cleaning up", "01-12-cleaning-up", False, ["dk-rm", "dk-images"]),
     ]),
    ("02-images-dockerfile", "Images, Layers & the Dockerfile",
     "notebooks/02-images-layers-and-the-dockerfile.ipynb", [
        ("What is an image, really?", "02-02-what-is-an-image-really", True, ["dk-image"]),
        ("Layers and the union filesystem", "02-03-layers-and-the-union-filesystem", True,
         ["dk-layer", "dk-unionfs", "dk-overlay2"]),
        ("Image references — the full name of an image", "02-04-image-references", True,
         ["dk-img-tag", "dk-tag", "dk-digest-pin"]),
        ("Inspecting images — `inspect` and `history`", "02-05-inspecting-images", False,
         ["dk-image", "dk-manifest", "dk-digest"]),
        ("Meet the Dockerfile", "02-06-meet-the-dockerfile", True, ["dk-dockerfile"]),
        ("`FROM` — the base layer", "02-07-from-the-base-layer", True, ["dk-df-from", "dk-layer"]),
        ("`RUN` — execute at build time", "02-08-run-execute-at-build-time", True, ["dk-df-run", "dk-layer"]),
        ("`COPY` vs `ADD`", "02-09-copy-vs-add", False, ["dk-df-copy"]),
        ("`WORKDIR`, `ENV`, `ARG`, `EXPOSE`, `USER`, `LABEL`, `HEALTHCHECK`",
         "02-10-workdir-env-arg-expose-user-label-healthcheck", False,
         ["dk-df-workdir", "dk-df-env", "dk-df-arg"]),
        ("`CMD` vs `ENTRYPOINT` — the confusing pair", "02-11-cmd-vs-entrypoint", True,
         ["dk-df-cmd", "dk-df-entry"]),
        ("The build context", "02-12-the-build-context", False, ["dk-dockerfile", "dk-build"]),
        ("`.dockerignore`", "02-13-dockerignore", False, ["dk-dockerfile"]),
        ("A real build — Python Flask app", "02-14-a-real-build-flask-app", True,
         ["dk-build", "dk-buildkit", "dk-image"]),
        ("Multi-stage builds", "02-15-multi-stage-builds", True, ["dk-multistage", "dk-buildkit"]),
        ("BuildKit and `docker buildx`", "02-16-buildkit-and-buildx", True, ["dk-buildkit", "dk-build"]),
        ("Tagging conventions", "02-17-tagging-conventions", False, ["dk-img-tag", "dk-tag", "dk-digest-pin"]),
     ]),
    ("03-running-containers", "Running & Inspecting Containers",
     "notebooks/03-running-and-inspecting-containers.ipynb", [
        ("The full anatomy of `docker run`", "03-02-the-full-anatomy-of-docker-run", True,
         ["dk-run", "dk-container"]),
        ("Foreground, detached, interactive — what `-d`, `-i`, `-t` actually do",
         "03-03-foreground-detached-interactive", True, ["dk-run"]),
        ("Naming, hostname, and `--rm`", "03-04-naming-hostname-and-rm", False, ["dk-run", "dk-rm"]),
        ("The lifecycle in depth", "03-05-the-lifecycle-in-depth", True, ["dk-lifecycle"]),
        ("Restart policies", "03-06-restart-policies", False, ["dk-lifecycle", "dk-start"]),
        ("Resource limits", "03-07-resource-limits", True, ["dk-cgroups"]),
        ("Environment variables — `-e` and `--env-file`", "03-08-environment-variables", False, ["dk-run"]),
        ("Logs", "03-09-logs", False, ["dk-logs", "dk-dockerd"]),
        ("Looking inside a running container — `exec`, `attach`, `inspect`, `top`, `stats`, `diff`",
         "03-10-looking-inside-a-running-container", True,
         ["dk-exec", "dk-inspect", "dk-ps", "dk-container"]),
        ("Moving files in and out — `docker cp`", "03-11-moving-files-in-and-out", False,
         ["dk-container", "dk-vol-bind"]),
        ("Snapshotting — `docker commit`", "03-12-snapshotting-docker-commit", False,
         ["dk-image", "dk-container"]),
        ("Live-updating limits — `docker update`", "03-13-live-updating-limits-docker-update", False,
         ["dk-cgroups", "dk-container"]),
     ]),
    ("04-storage-volumes", "Storage, Volumes & Bind Mounts",
     "notebooks/04-storage-volumes-and-bind-mounts.ipynb", [
        ("Why the container filesystem isn't enough", "04-02-why-the-container-filesystem-isnt-enough",
         True, ["dk-layer", "dk-overlay2", "dk-container"]),
        ("The three mount types", "04-03-the-three-mount-types", True, ["dk-volumes"]),
        ("Named volumes — the default choice", "04-04-named-volumes", True, ["dk-vol-named"]),
        ("Anonymous volumes and `VOLUME` in Dockerfile", "04-05-anonymous-volumes-and-volume-instruction",
         False, ["dk-vol-named"]),
        ("Bind mounts — host paths into containers", "04-06-bind-mounts", True, ["dk-vol-bind"]),
        ("`tmpfs` — RAM-backed mounts", "04-07-tmpfs-ram-backed-mounts", False, ["dk-vol-tmpfs"]),
        ("`-v` short form vs `--mount` long form", "04-08-v-short-form-vs-mount-long-form", False,
         ["dk-volumes"]),
        ("Volume drivers", "04-09-volume-drivers", False, ["dk-vol-driver"]),
        ("Sharing volumes between containers", "04-10-sharing-volumes-between-containers", False,
         ["dk-volumes", "dk-container"]),
        ("The Mac / Windows file-sync caveat", "04-11-mac-windows-file-sync-caveat", False, ["dk-vol-bind"]),
        ("Backup, restore, migrate", "04-12-backup-restore-migrate", False, ["dk-vol-named"]),
        ("UID / GID gotchas", "04-13-uid-gid-gotchas", False, ["dk-vol-bind", "dk-ns-user"]),
        ("Where data actually lives", "04-14-where-data-actually-lives", False,
         ["dk-overlay2", "dk-vol-driver"]),
     ]),
    ("05-networking", "Networking & Port Publishing",
     "notebooks/05-networking-and-port-publishing.ipynb", [
        ("The mental model", "05-02-the-mental-model", True, ["dk-networks", "dk-container"]),
        ("The default `bridge` network", "05-03-the-default-bridge-network", True, ["dk-net-bridge"]),
        ("User-defined bridges — the standard choice", "05-04-user-defined-bridges", True, ["dk-net-bridge"]),
        ("The five built-in drivers", "05-05-the-five-built-in-drivers", True, ["dk-networks"]),
        ("Publishing ports", "05-06-publishing-ports", True, ["dk-ports", "dk-port-publish"]),
        ("What `-p` actually does under the hood", "05-07-what-p-actually-does", False,
         ["dk-port-publish", "dk-dockerd"]),
        ("`host` network mode — share the host's stack", "05-08-host-network-mode", False, ["dk-net-host"]),
        ("`none` — no network", "05-09-none-no-network", False, ["dk-net-none"]),
        ("Inspecting networks", "05-10-inspecting-networks", False, ["dk-networks"]),
        ("Connect / disconnect at runtime", "05-11-connect-disconnect-at-runtime", False,
         ["dk-networks", "dk-container"]),
        ("DNS configuration", "05-12-dns-configuration", False, ["dk-networks"]),
        ("`overlay` — multi-host networks (preview)", "05-13-overlay-multi-host-networks", False,
         ["dk-net-overlay", "dk-sw-overlay-net"]),
        ("`macvlan` / `ipvlan` — real LAN IPs", "05-14-macvlan-ipvlan", False, ["dk-networks"]),
     ]),
    ("06-compose", "Docker Compose & Multi-Container Apps",
     "notebooks/06-docker-compose-and-multi-container-apps.ipynb", [
        ("Why Compose", "06-02-why-compose", True, ["dk-compose"]),
        ("The `compose.yaml` shape", "06-03-the-compose-yaml-shape", True, ["dk-compose"]),
        ("A first compose file — web + db", "06-04-a-first-compose-file", True,
         ["dk-cmp-services", "dk-cmp-depends"]),
        ("The everyday commands", "06-05-the-everyday-commands", False, ["dk-compose", "dk-dockerd"]),
        ("`build:` vs `image:`", "06-06-build-vs-image", False, ["dk-cmp-services", "dk-build"]),
        ("`depends_on` with healthchecks — startup order that actually works",
         "06-07-depends-on-with-healthchecks", True, ["dk-cmp-depends"]),
        ("Networks and volumes in Compose", "06-08-networks-and-volumes-in-compose", False,
         ["dk-cmp-networks", "dk-cmp-volumes"]),
        ("Environment — three layers and an `.env` file", "06-09-environment-and-env-file", False,
         ["dk-cmp-services"]),
        ("Profiles — opt-in services", "06-10-profiles", False, ["dk-cmp-services"]),
        ("Overrides — layering compose files", "06-11-overrides", False, ["dk-compose"]),
        ("Project name — what it means and why duplicates collide", "06-12-project-name", False,
         ["dk-compose"]),
        ("Scaling — and what it does (and doesn't) give you", "06-13-scaling", False,
         ["dk-cmp-services", "dk-sw-service"]),
        ("A realistic stack — Flask + Postgres + Redis, end to end", "06-14-a-realistic-stack", True,
         ["dk-compose"]),
     ]),
    ("07-registries", "Registries, Tags & Distribution",
     "notebooks/07-registries-tags-and-distribution.ipynb", [
        ("What a registry actually is", "07-02-what-a-registry-actually-is", True, ["dk-registry"]),
        ("Docker Hub and the alternatives", "07-03-docker-hub-and-the-alternatives", True,
         ["dk-hub", "dk-private"]),
        ("The push/pull workflow", "07-04-the-push-and-pull-workflow", True,
         ["dk-reg-push", "dk-reg-pull", "dk-dockerd"]),
        ("Authentication", "07-05-authentication", False, ["dk-registry", "dk-private"]),
        ("Image references revisited", "07-06-image-references-revisited", False,
         ["dk-tag", "dk-digest-pin"]),
        ("Tagging conventions in practice", "07-07-tagging-conventions-in-practice", False,
         ["dk-tag", "dk-img-tag"]),
        ("Image manifests and digests", "07-08-image-manifests-and-digests", True,
         ["dk-manifest", "dk-digest", "dk-digest-pin"]),
        ("Manifest lists — one tag, many architectures", "07-09-manifest-lists", False, ["dk-manifest"]),
        ("Running a local registry", "07-10-running-a-local-registry", False, ["dk-private"]),
        ("Mirroring and pull-through caching", "07-11-mirroring-and-pull-through-caching", False,
         ["dk-private", "dk-reg-pull"]),
        ("Garbage collection on a registry", "07-12-garbage-collection", False, ["dk-registry"]),
        ("Image scanning preview", "07-13-image-scanning-preview", False, ["dk-sec-scan", "dk-sec-sbom"]),
     ]),
    ("08-security", "Security, Secrets & Hardening",
     "notebooks/08-security-secrets-and-hardening.ipynb", [
        ("The container threat model", "08-02-the-container-threat-model", True,
         ["dk-security", "dk-container"]),
        ("The kernel primitives revisited", "08-03-the-kernel-primitives-revisited", True,
         ["dk-ns-pid", "dk-ns-net", "dk-ns-user", "dk-cgroups", "dk-caps"]),
        ("The \"root in container\" problem", "08-04-the-root-in-container-problem", True,
         ["dk-ns-user", "dk-caps"]),
        ("Running as non-root", "08-05-running-as-non-root", True, ["dk-sec-rootless", "dk-ns-user"]),
        ("User-namespace remapping", "08-06-user-namespace-remapping", False,
         ["dk-ns-user", "dk-sec-rootless"]),
        ("Rootless Docker", "08-07-rootless-docker", False, ["dk-sec-rootless"]),
        ("Linux capabilities — drop everything, add what you need", "08-08-linux-capabilities", True,
         ["dk-caps", "dk-sec-capsdrop"]),
        ("Seccomp profiles", "08-09-seccomp-profiles", False, ["dk-sec-seccomp", "dk-caps"]),
        ("AppArmor and SELinux", "08-10-apparmor-and-selinux", False, ["dk-sec-apparmor"]),
        ("Read-only root filesystem", "08-11-read-only-root-filesystem", False, ["dk-sec-readonly"]),
        ("`no-new-privileges`", "08-12-no-new-privileges", False, ["dk-sec-capsdrop", "dk-caps"]),
        ("Secrets — and why env vars aren't secret", "08-13-secrets", True, ["dk-sec-secrets"]),
        ("Image signing", "08-14-image-signing", False, ["dk-digest-pin", "dk-registry"]),
        ("Supply-chain hygiene — SBOMs, provenance, attestations", "08-15-supply-chain-hygiene", False,
         ["dk-sec-sbom", "dk-sec-scan"]),
        ("Putting it together — the hardened service", "08-16-the-hardened-service", True, ["dk-security"]),
     ]),
    ("09-swarm", "Orchestration with Swarm",
     "notebooks/09-orchestration-with-swarm.ipynb", [
        ("Why orchestration", "09-02-why-orchestration", True, ["dk-orchestrate"]),
        ("Swarm vs Kubernetes", "09-03-swarm-vs-kubernetes", False, ["dk-swarm"]),
        ("Swarm architecture", "09-04-swarm-architecture", True, ["dk-sw-manager", "dk-sw-worker"]),
        ("Initialising a cluster", "09-05-initialising-a-cluster", True, ["dk-sw-manager", "dk-sw-worker"]),
        ("Services, not containers", "09-06-services-not-containers", True,
         ["dk-sw-service", "dk-sw-task", "dk-container"]),
        ("The service lifecycle", "09-07-the-service-lifecycle", False, ["dk-sw-service", "dk-sw-task"]),
        ("Rolling updates and rollback", "09-08-rolling-updates-and-rollback", True, ["dk-sw-service"]),
        ("Overlay networks revisited", "09-09-overlay-networks-revisited", True,
         ["dk-sw-overlay-net", "dk-net-overlay"]),
        ("The ingress network and routing mesh", "09-10-the-ingress-network-and-routing-mesh", True,
         ["dk-sw-mesh", "dk-sw-overlay-net"]),
        ("Stacks — the Compose file in cluster form", "09-11-stacks", True, ["dk-compose", "dk-swarm"]),
        ("Service discovery and DNS", "09-12-service-discovery-and-dns", False,
         ["dk-sw-service", "dk-sw-overlay-net"]),
        ("Swarm secrets and configs", "09-13-swarm-secrets-and-configs", False,
         ["dk-sec-secrets", "dk-swarm"]),
        ("Placement — putting tasks on the right nodes", "09-14-placement", False,
         ["dk-sw-task", "dk-sw-worker"]),
        ("Node management", "09-15-node-management", False, ["dk-sw-manager", "dk-sw-worker"]),
        ("The realities — Swarm in 2026", "09-16-the-realities-swarm-today", False, ["dk-swarm"]),
     ]),
    ("10-install-dca", "Install, Configure, Troubleshoot & DCA Prep",
     "notebooks/10-install-configure-troubleshoot-and-dca-prep.ipynb", [
        ("Installing Docker Engine on Linux", "10-02-installing-docker-engine-on-linux", True, ["dk-engine"]),
        ("Post-install", "10-03-post-install", False, ["dk-engine", "dk-dockerd"]),
        ("Rootless Docker — the alternative install", "10-04-rootless-docker", False, ["dk-sec-rootless"]),
        ("The daemon configuration — `/etc/docker/daemon.json`", "10-05-the-daemon-configuration", True,
         ["dk-dockerd"]),
        ("Storage drivers", "10-06-storage-drivers", False, ["dk-overlay2", "dk-unionfs"]),
        ("Logging drivers", "10-07-logging-drivers", False, ["dk-logs", "dk-dockerd"]),
        ("The runtime layer — `containerd`, `runc`, alternatives", "10-08-the-runtime-layer", True,
         ["dk-containerd", "dk-runc"]),
        ("Daemon troubleshooting", "10-09-daemon-troubleshooting", False, ["dk-dockerd"]),
        ("The container troubleshooting playbook", "10-10-the-container-troubleshooting-playbook", True,
         ["dk-container", "dk-ps", "dk-logs", "dk-inspect"]),
        ("Build troubleshooting", "10-11-build-troubleshooting", False, ["dk-buildkit", "dk-build"]),
        ("Network troubleshooting", "10-12-network-troubleshooting", False, ["dk-networks", "dk-ports"]),
        ("The DCA exam itself", "10-13-the-dca-exam-itself", True, None),
        ("Exam-prep tactics", "10-14-exam-prep-tactics", False, None),
        ("Where to go next", "10-15-where-to-go-next", False, None),
     ]),
]

presentations = []
for pid, title, notebook, sections in MODULES:
    overlay = [{
        "heading": "What's covered",
        "scene": S, "spine": True, "role": "hook",
    }]
    for heading, stem, spine, highlight in sections:
        entry = {"heading": heading, "scene": S, "spine": spine}
        if highlight:
            entry["highlight"] = highlight
            entry["focus"] = highlight
        entry["audio"] = f"audio/{stem}.wav"
        overlay.append(entry)
    presentations.append({
        "id": pid, "title": title, "notebook": notebook,
        "defaultScene": S, "sections": overlay,
    })

manifest = {
    "concept": "Docker",
    "design": "DESIGN.md",
    "scenes": [
        {"id": "docker", "title": "Docker — the full platform", "status": "built"},
    ],
    "presentations": presentations,
}

out = Path(__file__).resolve().parent.parent / "manifest.json"
out.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
n = sum(len(p["sections"]) for p in presentations)
print(f"wrote {out} — {len(presentations)} modules, {n} sections")
